# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Flickr-Tools
version:      0.02
version_from: 
installdirs:  site
requires:
    Flickr::API:                   0
    Test::MockObject:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
